apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    name: locust-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust-master
  template:
    metadata:
      labels:
        app: locust-master
    spec:
      containers:
        - name: locust-master
          image: azranger.azurecr.io/locust-aks:v1.2
          env:
            - name: LOCUST_MODE
              value: master
            - name: TARGET_HOST
              value: https://acsatraining.azurefd.net
          ports:
            - name: loc-master-web
              containerPort: 8089
              protocol: TCP
            - name: loc-master-p1
              containerPort: 5557
              protocol: TCP
            - name: loc-master-p2
              containerPort: 5558
              protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    name: locust-worker
spec:
  replicas: 20
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
        - name: locust-worker
          image: azranger.azurecr.io/locust-aks:v1.2
          resources:
            requests: # minimum resources required
              cpu: 250m
              memory: 512Mi
            limits: # maximum resources allocated
              cpu: 250m
              memory: 512Mi
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER_URL
              value: locust-master
            - name: TARGET_HOST
              value: https://acsatraining.azurefd.net
---
kind: Service
apiVersion: v1
metadata:
  name: locust-master
  labels:
    app: locust-master
spec:
  ports:
    - port: 5557
      targetPort: loc-master-p1
      protocol: TCP
      name: loc-master-p1
    - port: 5558
      targetPort: loc-master-p2
      protocol: TCP
      name: loc-master-p2
  selector:
    app: locust-master
---
kind: Service
apiVersion: v1
metadata:
  name: locust-master-ui
  labels:
    app: locust-master
spec:
  ports:
    - port: 8089
      targetPort: loc-master-web
      protocol: TCP
  selector:
    app: locust-master
  type: LoadBalancer
